#!/bin/sh

MOUNT_DIR="${1}"

# setup wifi if there is a wpa_supplicant.conf on SD
if [ -f  "${MOUNT_DIR}/wpa_supplicant.conf" ];then
  apk add wireless-tools wpa_supplicant
  mkdir -p /etc/wpa_supplicant/
  cp "${MOUNT_DIR}/wpa_supplicant.conf" /etc/wpa_supplicant/wpa_supplicant.conf
  /etc/init.d/wpa_supplicant start
fi

# start ssh if there is a ssh file on SD
if [ -f  "${MOUNT_DIR}/ssh" ];then
  apk add openssh
  /etc/init.d/sshd start
fi

# copy ssh config, if it's on SD, so you can override settings
if [ -f  "${MOUNT_DIR}/sshd_config" ];then
  mkdir -p /etc/ssh/
  cp "${MOUNT_DIR}/sshd_config" /etc/ssh/
fi